sudo: required

services:
  - docker
language: python
env:
  - BIGTABLE_EMULATOR_HOST=localhost:8080 CATTLEDB_CONFIGURATION=testing
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - docker run -d -p 127.0.0.1:8080:8080 spotify/bigtable-emulator:latest
  - docker ps -a
  - sleep 5
install:
  - pip install -r requirements_server.txt
  - pip install -r requirements.txt
  - pip install pytest mock
  - pip install .
before_script:
  - sleep 1
script:
  - pytest tests
after_success:
  - sleep 1
